### ISSUE TITLE
I set n_jobs=6  in GibbsDPHM,but there is only one CPU used in my server.

### ISSUE THREAD

**Issue by liuziyang365** [tahmidmehdi/dphmix#1]

**Comment by tahmidmehdi** [comment]
The GibbsDPHM's fit_predict method only uses multiple cores for parameter sampling, which is just one step of each iteration. All other steps, like hyperparameter updates, use just 1 core. I think you may have queried the number of cores during one of these other steps.

**Comment by liuziyang365** [comment]
Thanks a lot. There is another question. When I set cl(can't-link constraints) in GibbsDPHM,I only get one cluster in the result.

**Comment by liuziyang365** [comment]
ps:I only get one cluster when I set each sample with cl(can't-link constraints) in the dataset.(There are 2 classes in the dataset,I want to know the clusters in each class)

**Comment by tahmidmehdi** [comment]
I found the issue. When you use a cl constraint and there is currently only 1 cluster (call it cluster 0), a data point in the cl constraint should get cluster 1 but gets reassigned to cluster 0. I will fix it. Thanks for letting me know!

**Comment by tahmidmehdi** [comment]
Ok. I've released dphmix 0.2.0. GibbsDPHM should satisfy cl constraints now.
